"""
Phase 9 Step 5 — Section-based supervisor.

Reads AgentOutputs produced by the coordinator and generates a ResearchBrief
whose sections are driven entirely by ResearchPreset.report_sections.

Rules (hard):
  - At most THREE LLM calls per run: one initial call plus two JSON-repair
    retries when parsing/validation fails.
  - LLM prompt uses only AgentOutput.{findings, summary, risks, missing_data,
    sources} — never prior/external knowledge.
  - Disclaimer is hardcoded; never generated by the LLM.
  - sources_summary is built from SourceRef objects; never fabricated.
  - Post-generation safety filter strips preset.banned_terms from all text.
  - If LLM fails/times-out → deterministic fallback from agent summaries.
  - No network access, no Tavily, no memory, no raw logs.

Thread model:
  _call_llm() is blocking (Anthropic HTTP).  SupervisorReportWriter owns a
  short-lived per-run ThreadPoolExecutor so asyncio.run() does not hang.
"""

from __future__ import annotations

import asyncio
import concurrent.futures
import os
import sys
import time
from pathlib import Path
from typing import Any

_RESEARCH_DIR = Path(__file__).parent
if str(_RESEARCH_DIR) not in sys.path:
    sys.path.insert(0, str(_RESEARCH_DIR))

import logging

try:
    from .schema import (
        AgentOutput, ContextPack, ContextPackItem, CostEstimate,
        RetrievalTrace, ResearchBrief,
        ResearchPreset, ResearchSection, ResearchTask, now_iso,
    )
    from .llm_bridge import call_llm as _call_llm_bridge
    from .structured_llm import call_json_with_repair
    from .evidence_store import EvidenceStore
except ImportError:
    from schema import (  # type: ignore[no-redef]
        AgentOutput, ContextPack, ContextPackItem, CostEstimate,
        RetrievalTrace, ResearchBrief,
        ResearchPreset, ResearchSection, ResearchTask, now_iso,
    )
    from llm_bridge import call_llm as _call_llm_bridge  # type: ignore[no-redef]
    from structured_llm import call_json_with_repair  # type: ignore[no-redef]
    from evidence_store import EvidenceStore  # type: ignore[no-redef]

_log = logging.getLogger(__name__)

if os.environ.get("FX_AUDIT_DEBUG", ""):
    _log.setLevel(logging.DEBUG)
    if not any(h for h in _log.handlers if getattr(h, "_audit", False)):
        _h = logging.StreamHandler()
        _h.setLevel(logging.DEBUG)
        _h.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))
        _h._audit = True  # type: ignore[attr-defined]
        _log.addHandler(_h)

# ── Constants ─────────────────────────────────────────────────────────────────

_LLM_MODEL      = "deepseek-chat"
_LLM_MAX_TOKENS = 2048
_LLM_JSON_REPAIR_RETRIES = 2
_DEEPSEEK_CHAT_INPUT_PER_TOKEN  = 0.27 / 1_000_000
_DEEPSEEK_CHAT_OUTPUT_PER_TOKEN = 1.10 / 1_000_000
_SAFE_REPLACEMENT = "（已移除）"

# ── ContextPack token budget (unit: characters, not LLM tokens) ──────────
_CONTEXT_PACK_TOKEN_BUDGET = 7500
_MAX_COMPLETION_TOKENS = 1800
_MAX_CHUNKS_PER_SECTION = 5
_MAX_CHUNK_TOKENS = 1200
_SECTION_TOKEN_RESERVES: dict[str, int] = {
    "fx_price":   1800,
    "news_event":  800,
    "macro":      2200,
    "risk":       1000,
}

# Hard-coded disclaimer — NEVER generated by the LLM.
_DISCLAIMER = (
    "⚠️ 本简报仅供参考，不构成任何投资建议或换汇操作建议。"
    "外汇市场存在风险，请结合自身情况做出判断。"
)


# ── LLM caller — delegates to llm_bridge (Anthropic → DeepSeek fallback) ──────

def _call_llm(
    prompt: str,
    system: str,
    max_tokens: int = _LLM_MAX_TOKENS,
) -> tuple[str, dict[str, int]]:
    """Thin wrapper; real logic is in llm_bridge.call_llm()."""
    return _call_llm_bridge(prompt, system, max_tokens=max_tokens, timeout=45.0)


# ── Prompt builder ────────────────────────────────────────────────────────────

def _agent_block(output: AgentOutput) -> str:
    """Format one agent's output as a concise text block for the LLM prompt."""
    lines = [f"=== {output.agent_name.upper()} [status={output.status}] ==="]

    if output.status == "error":
        lines.append(f"错误：{output.error or '数据不可用'}")
        return "\n".join(lines)

    if output.summary:
        lines.append(f"摘要: {output.summary[:300]}")

    if output.findings:
        lines.append("发现:")
        for f in output.findings[:8]:
            direction = f"[{f.direction}] " if f.direction else ""
            lines.append(f"  - {direction}{f.summary[:200]}")

    if output.risks:
        lines.append("风险:")
        for r in output.risks[:4]:
            lines.append(f"  - {r[:150]}")

    if output.missing_data:
        gaps = ", ".join(output.missing_data[:4])
        lines.append(f"缺失数据: {gaps}")

    return "\n".join(lines)


def _build_prompt(
    task: ResearchTask,
    preset: ResearchPreset,
    outputs: list[AgentOutput],
) -> tuple[str, str]:
    """
    Build (system_prompt, user_prompt) for the single LLM call.

    The prompt instructs the LLM to:
      - Use only the supplied agent data (no prior knowledge)
      - Fill every section in preset.report_sections in order
      - Return a single valid JSON object
      - Never use banned_terms
      - Use neutral research-assistant language (no trade/invest advice)
    """
    banned_str = "、".join(preset.banned_terms) if preset.banned_terms else "（无）"

    system = (
        "你是研究简报撰写助理。\n"
        "严格规则：\n"
        "1. 只使用用户提供的代理研究数据，绝对禁止添加任何模型先验知识或外部信息。\n"
        "2. 不给任何投资建议、换汇建议或操作建议；使用研究助理的中立描述措辞。\n"
        f"3. 禁止用词（出现须替换为'（数据已过滤）'）：{banned_str}。\n"
        "4. 若某代理 status=error 或 status=partial，在相关章节注明数据缺失，不推测。\n"
        "5. 汇率口径硬性要求：面向用户的人民币/澳元报价一律写作“1 AUD = X CNY”；"
        "解释方向时写“AUD 相对 CNY 走强/走弱”或“CNY 相对 AUD 走强/走弱”。"
        "不要把 4.x 这类数值称为“CNY/AUD 汇率”。\n"
        "6. 输出必须是合法 JSON，不包含任何 JSON 以外的文字或 markdown 代码块。\n"
        f"7. 输出语言：{preset.output_language}。"
    )

    known_agent_names = sorted({o.agent_name for o in outputs})
    data_blocks = "\n\n".join(_agent_block(o) for o in outputs)

    sections_numbered = "\n".join(
        f"  {i + 1}. {s}" for i, s in enumerate(preset.report_sections)
    )
    purpose_hint = task.safe_user_context.purpose or "通用"

    user = (
        f"研究主题：{task.research_topic}\n"
        f"关注货币对：{task.focus_pair or '未指定'}\n"
        f"用途场景：{purpose_hint}\n\n"
        "━━━ 研究数据（来源：各代理输出）━━━\n"
        f"{data_blocks}\n\n"
        "━━━ 生成任务 ━━━\n"
        f"请为以下 {len(preset.report_sections)} 个章节生成内容，顺序与列表一致：\n"
        f"{sections_numbered}\n\n"
        f"可使用的代理名称：{', '.join(known_agent_names)}\n\n"
        "输出格式（严格 JSON，无额外文字）：\n"
        "{\n"
        '  "conclusion": "一句话总结，不含操作建议",\n'
        '  "sections": [\n'
        '    {\n'
        '      "title": "<与上方章节列表完全匹配的标题>",\n'
        '      "content": "<章节内容，仅基于代理数据，每句话必须可追溯到上方代理输出>",\n'
        '      "source_agents": ["<仅使用上方列出的代理名>", ...]\n'
        '    }\n'
        "  ]\n"
        "}"
    )

    return system, user


def _build_prompt_from_context_pack(
    task: ResearchTask,
    preset: ResearchPreset,
    context_pack: ContextPack,
) -> tuple[str, str]:
    """Build (system, user) prompt from ContextPack evidence instead of raw AgentOutput."""
    banned_str = "、".join(preset.banned_terms) if preset.banned_terms else "（无）"

    system = (
        "你是研究简报撰写助理。\n"
        "严格规则：\n"
        "1. 仅使用下方 [Evidence] 块中提供的证据，绝对禁止添加模型先验知识或外部信息。\n"
        "2. 不给任何投资建议、换汇建议或操作建议；使用研究助理的中立描述措辞。\n"
        f"3. 禁止用词（出现须替换为'（数据已过滤）'）：{banned_str}。\n"
        "4. 尽可能为主要论点引用证据片段 ID（chunk_id），格式为 [chunk_id]。\n"
        "5. 若某章节缺少对应证据，如实报告数据缺口，不推测不补充。\n"
        "6. 汇率口径硬性要求：面向用户的人民币/澳元报价一律写作“1 AUD = X CNY”；"
        "解释方向时写“AUD 相对 CNY 走强/走弱”或“CNY 相对 AUD 走强/走弱”。"
        "不要把 4.x 这类数值称为“CNY/AUD 汇率”。\n"
        "7. 输出必须是合法 JSON，不包含任何 JSON 以外的文字或 markdown 代码块。\n"
        f"8. 输出语言：{preset.output_language}。"
    )

    evidence_blocks: list[str] = []
    for item in context_pack.items:
        evidence_blocks.append(
            f"--- chunk_id={item.chunk_id} agent={item.agent_name} ---\n"
            f"{item.text}"
        )
    evidence_text = "\n\n".join(evidence_blocks) if evidence_blocks else "（无可用证据）"

    sections_numbered = "\n".join(
        f"  {i + 1}. {s}" for i, s in enumerate(preset.report_sections)
    )
    purpose_hint = task.safe_user_context.purpose or "通用"
    chunk_id_list = [it.chunk_id for it in context_pack.items]

    user = (
        f"研究主题：{task.research_topic}\n"
        f"关注货币对：{task.focus_pair or '未指定'}\n"
        f"用途场景：{purpose_hint}\n\n"
        "━━━ 证据数据（来源：EvidenceStore 检索）━━━\n"
        f"{evidence_text}\n\n"
        f"可引用的 chunk_ids：{chunk_id_list}\n\n"
        "━━━ 生成任务 ━━━\n"
        f"请为以下 {len(preset.report_sections)} 个章节生成内容，顺序与列表一致：\n"
        f"{sections_numbered}\n\n"
        "输出格式（严格 JSON，无额外文字）：\n"
        "{\n"
        '  "conclusion": "一句话总结，不含操作建议",\n'
        '  "sections": [\n'
        '    {\n'
        '      "title": "<与上方章节列表完全匹配的标题>",\n'
        '      "content": "<章节内容，仅基于上方证据，关键论点用 [chunk_id] 引用>",\n'
        '      "source_agents": ["<贡献证据的代理名>", ...],\n'
        '      "chunk_ids": ["<本节引用的 chunk_id>", ...]\n'
        '    }\n'
        "  ]\n"
        "}"
    )

    return system, user


def _validate_supervisor_json(data: dict[str, Any]) -> None:
    sections = data.get("sections")
    if not isinstance(sections, list):
        raise TypeError("sections must be a list")
    for index, section in enumerate(sections):
        if not isinstance(section, dict):
            raise TypeError(f"sections[{index}] must be an object")
        for key in ("title", "content", "source_agents"):
            if key not in section:
                raise KeyError(f"sections[{index}] missing {key}")


def _normalise_fx_quote_convention(text: str) -> str:
    """Keep user-facing CNY/AUD wording aligned to 1 AUD = X CNY."""
    if not text:
        return text
    replacements = (
        ("CNY/AUD 汇率区间", "1 AUD = X CNY 口径区间"),
        ("CNY/AUD 汇率", "1 AUD = X CNY 口径"),
        ("AUD/CNY 汇率区间", "1 AUD = X CNY 口径区间"),
        ("AUD/CNY 汇率", "1 AUD = X CNY 口径"),
    )
    for old, new in replacements:
        text = text.replace(old, new)
    return text


# ── LLM response parser ───────────────────────────────────────────────────────

def _parse_llm_payload(
    raw: dict[str, Any],
    task: ResearchTask,
    preset: ResearchPreset,
    outputs: list[AgentOutput],
    cost_estimate: CostEstimate,
    token_usage: dict[str, int],
    context_pack: ContextPack | None = None,
    retrieval_traces: list[RetrievalTrace] | None = None,
) -> ResearchBrief:
    """
    Parse the LLM JSON and build a ResearchBrief.

    Sections are matched to preset.report_sections by title (case-insensitive).
    If the LLM omits a section it is filled with a safe placeholder.
    """
    conclusion = _normalise_fx_quote_convention(str(raw.get("conclusion", "")))
    # user_notes is never taken from LLM — generated deterministically below
    user_notes = _build_user_notes(task.safe_user_context)

    llm_sections: list[dict[str, Any]] = raw.get("sections", [])
    # index by lowercase title for fuzzy matching
    by_title: dict[str, dict[str, Any]] = {
        s.get("title", "").strip().lower(): s for s in llm_sections
    }

    agent_status_map = {o.agent_name: o.status for o in outputs}
    valid_agents     = set(agent_status_map)

    valid_chunk_ids = (
        {it.chunk_id for it in context_pack.items} if context_pack else set()
    )

    sections: list[ResearchSection] = []
    for title in preset.report_sections:
        raw_sec = by_title.get(title.strip().lower())
        if raw_sec is None:
            content      = "（本章节数据暂缺，请参考其他章节）"
            source_agents: list[str] = []
            has_gap       = True
            chunk_ids: list[str] = []
        else:
            content = (
                _normalise_fx_quote_convention(
                    str(raw_sec.get("content", "")).strip()
                )
                or "（无内容）"
            )
            source_agents = [
                a for a in (raw_sec.get("source_agents") or [])
                if a in valid_agents
            ]
            chunk_ids = [
                cid for cid in (raw_sec.get("chunk_ids") or [])
                if cid in valid_chunk_ids
            ]
            has_gap = any(
                agent_status_map.get(a, "ok") != "ok" for a in source_agents
            ) or not source_agents
            if not source_agents:
                content = content + "\n" + _UNVERIFIABLE_NOTE
                has_gap = True

        sections.append(ResearchSection(
            title        = title,
            content      = content,
            source_agents= source_agents,
            has_data_gap = has_gap,
            chunk_ids    = chunk_ids,
        ))

    # data_gaps: aggregate missing_data from error/partial agents
    data_gaps = _build_data_gaps(outputs)

    # sources_summary: from SourceRef objects only, never fabricated
    sources_summary = _build_sources_summary(outputs)

    cost_with_llm = CostEstimate(
        llm_calls          = cost_estimate.llm_calls + 1,
        estimated_tokens   = cost_estimate.estimated_tokens + sum(token_usage.values()),
        estimated_cost_usd = round(
            cost_estimate.estimated_cost_usd
            + int(token_usage.get("prompt_tokens", 0) or 0) * _DEEPSEEK_CHAT_INPUT_PER_TOKEN
            + int(token_usage.get("completion_tokens", 0) or 0) * _DEEPSEEK_CHAT_OUTPUT_PER_TOKEN,
            6,
        ),
        total_latency_ms   = cost_estimate.total_latency_ms,
    )

    return ResearchBrief(
        task_id        = task.task_id,
        preset_name    = task.preset_name,
        conclusion     = conclusion,
        sections       = sections,
        user_notes     = user_notes,
        data_gaps      = data_gaps,
        sources_summary= sources_summary,
        disclaimer     = _DISCLAIMER,              # hardcoded — never from LLM
        agent_statuses = agent_status_map,
        cost_estimate  = cost_with_llm,
        retrieval_traces = retrieval_traces or [],
    )


async def _run_llm_with_json_retries(
    task: ResearchTask,
    preset: ResearchPreset,
    outputs: list[AgentOutput],
    cost_estimate: CostEstimate,
    context_pack: ContextPack | None = None,
) -> ResearchBrief | None:
    """Call the supervisor LLM and retry JSON repair up to two times."""
    if context_pack is not None and context_pack.items:
        system, user = _build_prompt_from_context_pack(task, preset, context_pack)
        prompt_path = "context_pack"
    else:
        system, user = _build_prompt(task, preset, outputs)
        prompt_path = "agent_output"

    _log.info(
        "[AUDIT][supervisor][task=%s] prompt_path=%s system_len=%d user_len=%d",
        task.task_id, prompt_path, len(system), len(user),
    )
    _log.debug(
        "[AUDIT][supervisor][task=%s] system_prompt:\n%s", task.task_id, system,
    )
    _log.debug(
        "[AUDIT][supervisor][task=%s] user_prompt:\n%s", task.task_id, user,
    )

    schema_hint = (
        "{\n"
        '  "conclusion": "...",\n'
        '  "sections": [{"title": "...", "content": "...", "source_agents": ["fx_agent"]}]\n'
        "}"
    )

    with concurrent.futures.ThreadPoolExecutor(
        max_workers=1, thread_name_prefix="supervisor-llm"
    ) as executor:
        loop = asyncio.get_running_loop()
        result = await loop.run_in_executor(
            executor,
            lambda: call_json_with_repair(
                _call_llm,
                user,
                system,
                max_tokens=_LLM_MAX_TOKENS,
                required_keys=("conclusion", "sections"),
                validate=_validate_supervisor_json,
                repair_retries=_LLM_JSON_REPAIR_RETRIES,
                schema_hint=schema_hint,
            ),
        )

    _log.info(
        "[AUDIT][supervisor][task=%s] llm_result ok=%s attempts=%d "
        "prompt_tokens=%d completion_tokens=%d response_len=%d",
        task.task_id, result.ok, result.attempts,
        result.token_usage.get("prompt_tokens", 0),
        result.token_usage.get("completion_tokens", 0),
        len(result.text),
    )
    if result.error:
        _log.warning(
            "[AUDIT][supervisor][task=%s] llm_error: %s",
            task.task_id, result.error,
        )
    _log.debug(
        "[AUDIT][supervisor][task=%s] raw_response:\n%s", task.task_id, result.text,
    )

    if not result.ok or result.data is None:
        return None

    adjusted_cost = CostEstimate(
        llm_calls=cost_estimate.llm_calls + result.attempts - 1,
        estimated_tokens=cost_estimate.estimated_tokens,
        estimated_cost_usd=cost_estimate.estimated_cost_usd,
        total_latency_ms=cost_estimate.total_latency_ms,
    )
    retrieval_traces: list[RetrievalTrace] = []
    if context_pack is not None:
        try:
            with EvidenceStore() as store:
                retrieval_traces = store.list_traces(task.task_id)
        except Exception:  # noqa: BLE001
            pass

    return _parse_llm_payload(
        result.data,
        task,
        preset,
        outputs,
        adjusted_cost,
        result.token_usage,
        context_pack=context_pack,
        retrieval_traces=retrieval_traces,
    )


# ── Deterministic fallback ────────────────────────────────────────────────────

def _build_fallback_brief(
    task: ResearchTask,
    preset: ResearchPreset,
    outputs: list[AgentOutput],
    cost_estimate: CostEstimate,
) -> ResearchBrief:
    """
    Build a ResearchBrief without LLM — used when LLM is unavailable.

    Each section receives a bullet list of all agent summaries / error messages,
    clearly labelled.  Order follows preset.report_sections.
    """
    agent_status_map = {o.agent_name: o.status for o in outputs}

    # Build one fallback section content from ALL agents (generic — no mapping)
    fallback_content_lines: list[str] = []
    has_any_gap = False
    contributing: list[str] = []

    for o in outputs:
        if o.status == "error":
            has_any_gap = True
            fallback_content_lines.append(
                f"【{o.agent_name}】数据不可用：{o.error or '未知错误'}"
            )
        else:
            summary = o.summary or "（无摘要）"
            prefix = "（部分数据）" if o.status == "partial" else ""
            fallback_content_lines.append(f"【{o.agent_name}】{prefix}{summary}")
            contributing.append(o.agent_name)
            if o.status == "partial":
                has_any_gap = True

    shared_content = "\n".join(fallback_content_lines)

    sections = [
        ResearchSection(
            title        = title,
            content      = shared_content or "（暂无数据）",
            source_agents= list(contributing),
            has_data_gap = has_any_gap,
        )
        for title in preset.report_sections
    ]

    # Conclusion: use risk_agent summary if available, else first ok-agent summary
    conclusion = ""
    for preferred in ("risk_agent",):
        o = next((x for x in outputs if x.agent_name == preferred and x.status != "error"), None)
        if o and o.summary:
            conclusion = o.summary
            break
    if not conclusion:
        o = next((x for x in outputs if x.status == "ok" and x.summary), None)
        conclusion = o.summary if o else "（LLM 不可用，无法生成结论）"

    return ResearchBrief(
        task_id        = task.task_id,
        preset_name    = task.preset_name,
        conclusion     = conclusion,
        sections       = sections,
        user_notes     = _build_user_notes(task.safe_user_context),
        data_gaps      = _build_data_gaps(outputs),
        sources_summary= _build_sources_summary(outputs),
        disclaimer     = _DISCLAIMER,
        agent_statuses = agent_status_map,
        cost_estimate  = cost_estimate,
    )


# ── Utility helpers ───────────────────────────────────────────────────────────

def _build_data_gaps(outputs: list[AgentOutput]) -> str:
    """Aggregate missing-data entries from error / partial agents."""
    lines: list[str] = []
    for o in outputs:
        if o.status == "error":
            lines.append(f"[{o.agent_name}] 错误: {o.error or '不可用'}")
        elif o.status == "partial" and o.missing_data:
            items = "; ".join(o.missing_data[:4])
            lines.append(f"[{o.agent_name}] 数据不完整: {items}")
    return "\n".join(lines)


def _build_user_notes(safe_ctx: "SafeUserContext") -> str:
    """
    Deterministic user_notes derived solely from SafeUserContext.

    The LLM is never asked to generate user_notes — this function owns
    that responsibility so the output is verifiable and cannot introduce
    prior knowledge.
    """
    purpose_map = {
        "tuition":    "本报告适用于留学学费换汇参考场景。",
        "living":     "本报告适用于海外生活费换汇参考场景。",
        "investment": "本报告适用于投资参考场景，请结合专业意见使用。",
    }
    note = purpose_map.get(safe_ctx.purpose or "", "")
    if safe_ctx.risk_level == "low" and note:
        note += "您偏好低风险，请重点关注稳定信号。"
    elif safe_ctx.risk_level == "high" and note:
        note += "您偏好高风险，需注意波动区间。"
    return note


_UNVERIFIABLE_NOTE = "（注：本节来源代理不明确，内容需人工核实）"


def _build_sources_summary(outputs: list[AgentOutput]) -> str:
    """Build sources_summary from SourceRef objects only — never fabricated."""
    seen_urls: set[str] = set()
    lines: list[str] = []

    for o in outputs:
        for src in o.sources:
            if src.url in seen_urls:
                continue
            seen_urls.add(src.url)
            pub = f"  发布: {src.published_at}" if src.published_at else ""
            lines.append(f"- {src.title or src.url} [{src.source}]{pub}")

    return "\n".join(lines) if lines else ""


def _sanitize_text(text: str, banned_terms: list[str]) -> str:
    """Replace every banned term with _SAFE_REPLACEMENT."""
    for term in banned_terms:
        if term in text:
            text = text.replace(term, _SAFE_REPLACEMENT)
    return text


def _apply_banned_filter(
    brief: ResearchBrief,
    banned_terms: list[str],
) -> ResearchBrief:
    """
    Post-generation safety pass.

    Scans conclusion, user_notes, and every section's content.
    Replaces any banned term in-place.  Returns the (mutated) brief.
    """
    if not banned_terms:
        return brief

    brief.conclusion = _sanitize_text(brief.conclusion, banned_terms)
    brief.user_notes = _sanitize_text(brief.user_notes, banned_terms)

    for sec in brief.sections:
        sec.content = _sanitize_text(sec.content, banned_terms)

    return brief


# ── Public class ──────────────────────────────────────────────────────────────

class SupervisorReportWriter:
    """
    Section-based supervisor — generates ResearchBrief from coordinator outputs.

    Protocol:
        brief = await SupervisorReportWriter().run(task, preset, outputs, cost)

    Thread model:
        _call_llm() runs in a fresh short-lived ThreadPoolExecutor per-run so
        asyncio.run() exits cleanly without waiting for a class-level pool.
    """

    async def run(
        self,
        task: ResearchTask,
        preset: ResearchPreset,
        outputs: list[AgentOutput],
        cost_estimate: CostEstimate,
    ) -> ResearchBrief:
        """
        Generate ResearchBrief.

        Tries the LLM path first; falls back to deterministic brief on failure.
        Applies banned-term filter regardless of which path was taken.
        """
        brief: ResearchBrief | None = None

        # ── ContextPack path (non-fatal) ─────────────────────────────────────
        context_pack: ContextPack | None = None
        try:
            with EvidenceStore() as store:
                context_pack = store.build_context_pack(
                    task, preset, outputs,
                    max_chunks_per_section=_MAX_CHUNKS_PER_SECTION,
                    token_budget=_CONTEXT_PACK_TOKEN_BUDGET,
                    max_chunk_tokens=_MAX_CHUNK_TOKENS,
                    section_token_reserves=_SECTION_TOKEN_RESERVES,
                    safe_user_context=task.safe_user_context,
                )
            if not context_pack.items:
                context_pack = None
        except Exception:  # noqa: BLE001
            _log.warning("ContextPack build failed; falling back to agent prompts",
                         exc_info=True)
            context_pack = None

        # ── LLM path ─────────────────────────────────────────────────────────
        try:
            brief = await _run_llm_with_json_retries(
                task, preset, outputs, cost_estimate,
                context_pack=context_pack,
            )
        except Exception:  # noqa: BLE001
            brief = None

        # ── Fallback path ─────────────────────────────────────────────────────
        if brief is None:
            brief = _build_fallback_brief(task, preset, outputs, cost_estimate)

        # ── Post-generation safety filter ─────────────────────────────────────
        brief = _apply_banned_filter(brief, preset.banned_terms)

        return brief
