"""Structured personalization storage for Phase 8."""

from .user_profile_store import (
    ALLOWED_FEEDBACK_TOPICS,
    build_safe_user_context,
    clear_inferred_preferences,
    create_preference_declaration,
    delete_user_profile,
    format_inferred_preferences_display,
    get_or_create_user,
    get_news_feedback_context,
    get_due_news_feedback_contexts,
    get_news_feedback_rollup_status,
    get_user_category_feedback_summary,
    get_user_profile,
    init_db,
    list_preference_declarations,
    log_feedback_event,
    log_raw_event,
    mark_news_feedback_contexts_summarized,
    purge_expired_news_feedback_context,
    mark_onboarding_completed,
    purge_expired_raw_events,
    store_news_feedback_context,
    update_explicit_preferences,
    update_inferred_preferences,
    update_inferred_preferences_from_feedback,
    update_preference_declaration_status,
)
from .preference_agent import PreferenceAgentResult, run_preference_agent_for_user

__all__ = [
    "ALLOWED_FEEDBACK_TOPICS",
    "build_safe_user_context",
    "clear_inferred_preferences",
    "create_preference_declaration",
    "delete_user_profile",
    "format_inferred_preferences_display",
    "get_or_create_user",
    "get_news_feedback_context",
    "get_due_news_feedback_contexts",
    "get_news_feedback_rollup_status",
    "get_user_category_feedback_summary",
    "get_user_profile",
    "init_db",
    "list_preference_declarations",
    "log_feedback_event",
    "log_raw_event",
    "mark_news_feedback_contexts_summarized",
    "purge_expired_news_feedback_context",
    "mark_onboarding_completed",
    "purge_expired_raw_events",
    "store_news_feedback_context",
    "update_explicit_preferences",
    "update_inferred_preferences",
    "update_inferred_preferences_from_feedback",
    "update_preference_declaration_status",
    "PreferenceAgentResult",
    "run_preference_agent_for_user",
]
